<?php
return array (
  'site_title' => '猪悟能猪病工作组',
  'site_keywords' => '猪病网,猪病诊断,猪病防治,猪悟能兽医在线',
  'site_description' => '猪悟能兽医在线猪病网，国家认证执业兽医师专家在线坐诊，提供规模化猪场常见猪病的诊断防治，以及猪病的用药指导服务。',
  'site_copyright' => '&copy;right 版权所有',
  'site_code' => '',
  'corp_title' => '郑州牧一草堂电子商务有限公司',
  'tel' => '400-678-0034',
  'email' => '公司邮箱',
  'address' => '郑州市金水区花园路农科路交叉口万达中心1604',
  'icp' => '豫ICP备16000996号-5',
  'public_qrcode' => '',
  'is_verify' => '1',
  'default_verify' => '1',
  'is_email_verify' => '0',
  'list_count' => '15',
  'admin_list_count' => '15',
  'is_admin_cache' => '0',
  'is_feedback_list' => '1',
  'is_menu_position' => '0',
  'is_trace' => '0',
  'is_debug' => '1',
  'use_picture_model' => '["Album"]',
  'thumb_method' => '3',
  'thumb_width' => '400',
  'thumb_height' => '300',
  'default_image' => '',
  'is_water' => '0',
  'water_model' => '',
  'water_type' => 'text',
  'water_location' => '9',
  'water_image' => '',
  'water_image_opacity' => '100',
  'water_text' => '',
  'water_text_size' => '20',
  'water_text_color' => '#ffffff',
  'email_host' => 'smtp.163.com',
  'email_from' => '',
  'email_password' => '',
  'email_fromname' => 'EduaskCMS',
  'sms_keyid' => '',
  'sms_keysecret' => '',
  'yt_appid' => '',
  'yt_secretid' => '',
  'yt_secretkey' => '',
)
?>